import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class Diff {
	/*
	 * @param args file generated by the script (git diff) which contains the modified files
	 */
	public static void main(String[] args) throws IOException {
		
		if (args.length != 1) {
			System.out.println("File path as parameter must be provided.");
			return;
		}
		
		File file = new File(args[0]); 
		BufferedReader br = new BufferedReader(new FileReader(file)); 
		BufferedWriter bw = new BufferedWriter(new FileWriter(new File(file.getParentFile(),"Example.properties"))); 
		String st; 
		String content = "";
		// Include pattern consisting of a comma-separated list of the modified files
		while ((st = br.readLine()) != null) { 
			content += "**/" + st + ",";
		}
		int len = content.length();
		// Property that will be read by Kiuwan CLI
		bw.write("include.patterns="+content.subSequence(0, len-1));
		bw.close();
		br.close();
	}
}
